In [1]:
import numpy as np

# Creating hydraulic head values

Creation of extended random binary-valued $k_{x,ext}$ and $k_{y,ext}$ arrays with 2 columns and rows more than we will extract from the inverse analysis.
For the $h_{ext}$ we choose the first two rows and the left and right column with random values to calculate a fitting (dim x dim) array for the $h$-values using formula (3) from the nature paper. 

In [2]:
dim=4
k_l=1 #low permeability
k_h=2 #high permeability

k_x_ext=np.random.randint(k_l, k_h+1, size=(dim+2, dim+1) )
k_y_ext=np.random.randint(k_l, k_h+1, size=(dim+1, dim+2) )
h_ext=np.random.rand(dim+2, dim+2) 

In [3]:
#above fields were used to obtain simulated hydraulic heads - equation 3 from the paper
for i in range(1,dim+1):
    for j in range(1, dim+1):
        h_ext[i+1][j]=(1/k_x_ext[i][j-1])*(k_x_ext[i-1][j-1]*h_ext[i-1][j]+
                      k_y_ext[i-1][j-1]*h_ext[i][j-1]+
                      k_y_ext[i-1][j]*h_ext[i][j+1]-
                      (k_x_ext[i-1][j-1]+k_x_ext[i][j-j]+k_y_ext[i-1][j]+k_y_ext[i-1][j-1])*h_ext[i][j])

h = h_ext[2:,1:dim+1]
k_x= k_x_ext[2:,1:dim]
k_y= k_y_ext[2:,1:dim+1]

In [4]:
print("k_x_ext =", k_x_ext) #4 Zeilen, 3 Spalten
print("k_y_ext = ", k_y_ext)
print("h_ext =", h_ext)

k_x_ext = [[2 1 2 1 2]
 [1 2 2 1 1]
 [2 1 1 1 2]
 [2 2 1 2 1]
 [1 2 1 2 1]
 [1 1 1 1 2]]
k_y_ext =  [[2 1 1 2 2 1]
 [2 1 1 2 1 2]
 [1 2 1 2 2 1]
 [2 1 1 1 1 2]
 [1 2 1 2 1 2]]
h_ext = [[ 1.74315904e-01  5.85957848e-01  1.47729828e-01  8.08285413e-01
   5.73458968e-01  3.28881112e-02]
 [ 9.96811268e-01  3.19204475e-01  6.48520537e-01  9.16085099e-01
   7.92625559e-01  1.07016998e-02]
 [ 3.03036849e-01  1.89883192e+00 -6.05531372e-01 -8.23084057e-01
  -2.32872079e+00  5.93135126e-01]
 [ 2.72055920e-01 -5.53662235e+00  6.00597717e+00  2.33078565e+00
   1.37119173e+01  7.89376631e-01]
 [ 9.05796900e-01  2.74190153e+01 -2.26919267e+01  1.86220138e+01
  -4.60359086e+01  7.91557293e-01]
 [ 5.11748701e-01 -1.96467669e+02  8.57563086e+01 -1.40885105e+02
   1.38508474e+02  1.02422513e-01]]


In [5]:
print("k_x =", k_x) #4 Zeilen, 3 Spalten
print("k_y = ", k_y)
print("h =", h)

k_x = [[1 1 1]
 [2 1 2]
 [2 1 2]
 [1 1 1]]
k_y =  [[2 1 2 2]
 [1 1 1 1]
 [2 1 2 1]]
h = [[   1.89883192   -0.60553137   -0.82308406   -2.32872079]
 [  -5.53662235    6.00597717    2.33078565   13.7119173 ]
 [  27.41901529  -22.69192673   18.62201382  -46.03590865]
 [-196.46766938   85.75630855 -140.88510503  138.50847448]]
