In [7]:
from IPython.display import clear_output
from qiskit import Aer
from qiskit import IBMQ
from qiskit_optimization import QuadraticProgram
from qiskit import Aer
from qiskit.utils import QuantumInstance
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit.algorithms import QAOA
import numpy as np


In [3]:
clear_output()

# Creating hydraulic head values

In [ ]:
dim=4
k_l=1 #low permeability
k_h=2 #high permeability
#h_ij hydraulic head at node i
#kx_ij (ky_ij) horizontal (vertical) permeability 
k_x=np.random.randint(k_l, k_h+1, size=(dim+1, dim) )
k_y=np.random.randint(k_l, k_h+1, size=(dim, dim+1) )
h=np.random.rand(dim+1, dim+1) 


In [33]:
print(k_x)
print(k_y)
print(h)

[[2 2 1 1]
 [2 1 1 2]
 [2 2 1 2]
 [1 1 2 1]
 [2 2 2 2]]
[[2 2 1 1 2]
 [1 2 2 2 2]
 [2 2 2 2 2]
 [1 2 1 2 2]]
[[0.92420602 0.05889673 0.32580387 0.8604932  0.76175347]
 [0.56026595 0.89614219 0.6300212  0.72079525 0.52733733]
 [0.22493515 0.88513074 0.22599345 0.70024428 0.54373401]
 [0.36814606 0.27291549 0.56244359 0.6864244  0.53539089]
 [0.36350212 0.08958007 0.26524922 0.8374421  0.09943254]]


In [41]:
#above fields were used to obtain simulated hydraulic heads - equation 3 from the paper
for j in range(1,dim):
    for i in range(1, dim):
        h[i+1][j]=(1/k_x[i][j-1])*(k_x[i-1][j-1]*h[i-1][j]+
         k_y[i-1][j-1]*h[i][j-1]+
         k_y[i-1][j]*h[i][j+1]-
         (k_x[i-1][j-1]+k_x[i][j-j]+k_y[i-1][j]+k_y[i-1][j-1])*h[i][j])
        
print(h)  
#does not work properly...sorry, maybe use this values for now and I look into it tomorrow

[[  0.92420602   0.05889673   0.32580387   0.8604932    0.76175347]
 [  0.56026595   0.89614219   0.6300212    0.72079525   0.52733733]
 [  0.22493515  -2.33538487  -1.24546104  -1.58612452   0.54373401]
 [  0.36814606   7.93699576   0.75261486  10.42021281   0.53539089]
 [  0.36350212 -53.41548063  28.95519102 -30.76569495   0.09943254]]
